/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.admin.ui.pembelian;

import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import org.joda.money.CurrencyUnit;

/**
 *
 * @author ai
 */
public class Add extends javax.swing.JDialog {
private String id;
private achmad.rifai.erp1.entity.Pembelian p;
private java.awt.Frame f;
    /**
     * Creates new form Add
     */
    public Add(java.awt.Frame parent, boolean modal,String i,achmad.rifai.erp1.entity.Pembelian pe) {
        super(parent, modal);
        f=parent;
        id=i;
        p=pe;
        initComponents();
    }

    public Add(java.awt.Frame parent, boolean modal,String i) {
        super(parent, modal);
        f=parent;
        id=i;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tgl = new javax.swing.JComboBox<>();
        total = new javax.swing.JFormattedTextField();
        suplier = new javax.swing.JComboBox<>();
        struk = new javax.swing.JTextField();
        n = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pendataan Pembelian 1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Struk");

        jLabel2.setText("Suplier");

        jLabel3.setText("Tanggal");

        jLabel4.setText("Total");

        tgl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tglItemStateChanged(evt);
            }
        });

        total.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        total.setText("0");
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalKeyReleased(evt);
            }
        });

        suplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satu :" }));
        suplier.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                suplierItemStateChanged(evt);
            }
        });

        struk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                strukKeyReleased(evt);
            }
        });

        n.setText("Next");
        n.setEnabled(false);
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tgl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total)
                                    .addComponent(suplier, 0, 145, Short.MAX_VALUE)
                                    .addComponent(struk))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(struk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(suplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(n)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        supliere();
        tgle();
        if(p!=null)inisial();
    }//GEN-LAST:event_formWindowOpened

    private void strukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_strukKeyReleased
        if(!struk.getText().isEmpty()&&0<suplier.getSelectedIndex())try {
            achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
            achmad.rifai.erp1.entity.Pembelian p=
                    achmad.rifai.erp1.entity.Pembelian.of(d, struk.getText(), suplier.getItemAt(suplier.getSelectedIndex()),
                            tgl.getItemAt(tgl.getSelectedIndex()));
            if(p!=null)struk.setForeground(Color.red);
            else struk.setForeground(Color.BLACK);
            d.close();
        } catch (Exception ex) {
            achmad.rifai.erp1.util.Db.hindar(ex);
        }refresh();
    }//GEN-LAST:event_strukKeyReleased

    private void suplierItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_suplierItemStateChanged
        if(!struk.getText().isEmpty()&&0<suplier.getSelectedIndex())try {
            achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
            achmad.rifai.erp1.entity.Pembelian p=
                    achmad.rifai.erp1.entity.Pembelian.of(d, struk.getText(), suplier.getItemAt(suplier.getSelectedIndex()),
                            tgl.getItemAt(tgl.getSelectedIndex()));
            if(p!=null)suplier.setBackground(Color.red);
            else suplier.setBackground(Color.BLACK);
            d.close();
        } catch (Exception ex) {
            achmad.rifai.erp1.util.Db.hindar(ex);
        }refresh();
    }//GEN-LAST:event_suplierItemStateChanged

    private void tglItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tglItemStateChanged
        if(!struk.getText().isEmpty()&&0<suplier.getSelectedIndex())try {
            achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
            achmad.rifai.erp1.entity.Pembelian p=
                    achmad.rifai.erp1.entity.Pembelian.of(d, struk.getText(), suplier.getItemAt(suplier.getSelectedIndex()),
                            tgl.getItemAt(tgl.getSelectedIndex()));
            if(p!=null)tgl.setBackground(Color.red);
            else tgl.setBackground(Color.BLACK);
            d.close();
        } catch (Exception ex) {
            achmad.rifai.erp1.util.Db.hindar(ex);
        }refresh();
    }//GEN-LAST:event_tglItemStateChanged

    private void totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyReleased
        if(!total.getText().isEmpty()){
            if(total.isValid()){
                int i=Integer.parseInt(total.getText());
                if(i>=0)total.setForeground(Color.BLACK);
                else total.setForeground(Color.red);
            }else total.setForeground(Color.red);
        }refresh();
    }//GEN-LAST:event_totalKeyReleased

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        saving();
        new Add1(f,true,id,p).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int x=JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menutup dialog ini?", "Tutup?", JOptionPane.YES_NO_OPTION);
        if(x!=JOptionPane.YES_OPTION){
            saving();
            new Add(f,true,id,p).setVisible(true);
        }this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton n;
    private javax.swing.JTextField struk;
    private javax.swing.JComboBox<String> suplier;
    private javax.swing.JComboBox<java.sql.Date> tgl;
    private javax.swing.JFormattedTextField total;
    // End of variables declaration//GEN-END:variables

    private void supliere() {
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.erp1.entity.dao.DAOSuplier dao=new achmad.rifai.erp1.entity.dao.DAOSuplier(d);
        for(achmad.rifai.erp1.entity.Suplier s:dao.all())suplier.addItem(s.getKode());
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }
    }

    private void tgle() {
        java.sql.Date d1=java.sql.Date.valueOf(LocalDate.now()),d2;
        if(p!=null){
            if(p.getTgl().before(java.sql.Date.valueOf(d1.toLocalDate().minusYears(3))))d2=p.getTgl();
            else d2=java.sql.Date.valueOf(d1.toLocalDate().minusYears(3));
        }else d2=java.sql.Date.valueOf(d1.toLocalDate().minusYears(3));
        while(!d1.before(d2)){
            tgl.addItem(d1);
            d1=java.sql.Date.valueOf(d1.toLocalDate().minusDays(1));
        }
    }

    private void refresh() {
        n.setEnabled(!struk.getText().isEmpty()&&0<suplier.getSelectedIndex()&&Color.BLACK==struk.getForeground()&&
        Color.BLACK==suplier.getBackground()&&Color.BLACK==tgl.getBackground()&&!total.getText().isEmpty()&&Color.BLACK==total.getForeground());
    }

    private void inisial() {
        struk.setText(p.getStruk());
        struk.setEnabled(false);
        suplier.setSelectedItem(p.getSuplier());
        suplier.setEnabled(false);
        tgl.setSelectedItem(p.getTgl());
        tgl.setEnabled(false);
        total.setText(""+p.getHarga().getAmount().longValueExact());
        n.setEnabled(true);
    }

    private void saving() {
        if(p==null){
            p=new achmad.rifai.erp1.entity.Pembelian();
            p.setDeleted(false);
        }p.setStruk(struk.getText());
        p.setSuplier(suplier.getItemAt(suplier.getSelectedIndex()));
        p.setTgl(tgl.getItemAt(tgl.getSelectedIndex()));
        p.setHarga(org.joda.money.Money.of(CurrencyUnit.of("IDR"), Long.parseLong(total.getText())));
    }
}