/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.admin.ui.pembelian;

import org.joda.money.CurrencyUnit;

/**
 *
 * @author ai
 */
class Data extends javax.swing.JInternalFrame {
public void setData(achmad.rifai.erp1.entity.ItemBeli i){
    barang.setSelectedItem(i.getBarang());
    harga.setText(""+i.getHarga().getAmount().longValueExact());
    jumlah.setValue(i.getJumlah());
}

    public achmad.rifai.erp1.entity.ItemBeli getData(){
        achmad.rifai.erp1.entity.ItemBeli i=new achmad.rifai.erp1.entity.ItemBeli();
        i.setSatuan(satuan.getText());
        i.setBarang(barang.getItemAt(barang.getSelectedIndex()));
        i.setHarga(org.joda.money.Money.of(CurrencyUnit.of("IDR"), Long.parseLong(harga.getText())));
        i.setJumlah(Integer.parseInt(""+jumlah.getValue()));
        return i;
    }

    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
        barange();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        satuan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        barang = new javax.swing.JComboBox<>();
        harga = new javax.swing.JFormattedTextField();
        jumlah = new javax.swing.JSpinner();

        setClosable(true);

        jLabel1.setText("Barang");

        jLabel2.setText("Harga");

        satuan.setText("Satuan");

        jLabel4.setText("Jumlah");

        barang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                barangItemStateChanged(evt);
            }
        });

        harga.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jumlah.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(satuan))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(harga)
                        .addComponent(barang, 0, 155, Short.MAX_VALUE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satuan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_barangItemStateChanged
        if(0<barang.getSelectedIndex())try {
            achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
            achmad.rifai.erp1.entity.Barang b=achmad.rifai.erp1.entity.Barang.of(d, barang.getItemAt(barang.getSelectedIndex()));
            satuan.setText(b.getSatuan());
            d.close();
        } catch (Exception ex) {
            achmad.rifai.erp1.util.Db.hindar(ex);
        }
    }//GEN-LAST:event_barangItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> barang;
    private javax.swing.JFormattedTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jumlah;
    private javax.swing.JLabel satuan;
    // End of variables declaration//GEN-END:variables

    private void barange() {
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.erp1.entity.dao.DAOBarang dao=new achmad.rifai.erp1.entity.dao.DAOBarang(d);
        for(achmad.rifai.erp1.entity.Barang b:dao.all())barang.addItem(b.getKode());
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }
    }
}
