/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.suplier.ui.beli;

import java.time.LocalDate;
import org.joda.money.CurrencyUnit;

/**
 *
 * @author janoko
 */
public abstract class Add extends javax.swing.JInternalFrame {
private String id;
private achmad.rifai.erp1.entity.Pembelian p;
public abstract void entek();
    /**
     * Creates new form Add
     */
    public Add(String i) {
        id=i;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        brg = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jum = new javax.swing.JSpinner();
        total = new javax.swing.JFormattedTextField();
        sup = new javax.swing.JComboBox<>();
        struk = new javax.swing.JTextField();
        s = new javax.swing.JButton();

        setClosable(true);
        setTitle("Mendata Pembelian");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Struk");

        jLabel2.setText("Pemasok");

        brg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satu :" }));
        brg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brgItemStateChanged(evt);
            }
        });

        jLabel3.setText("Harga Total");

        jum.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jum.setEnabled(false);
        jum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jumStateChanged(evt);
            }
        });

        total.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total.setText("0");
        total.setEnabled(false);
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalKeyReleased(evt);
            }
        });

        sup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satu :" }));
        sup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                supItemStateChanged(evt);
            }
        });

        struk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                strukKeyReleased(evt);
            }
        });

        s.setText("Simpan");
        s.setEnabled(false);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jum)
                            .addComponent(total)
                            .addComponent(sup, 0, 179, Short.MAX_VALUE)
                            .addComponent(struk))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(struk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        new Thread(this::suplier).start();
        new Thread(this::barang).start();
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        p=new achmad.rifai.erp1.entity.Pembelian();
        p.setDeleted(false);
        p.setTgl(java.sql.Date.valueOf(LocalDate.now()));
        p.setTanggung(id);
        p.setItems(new java.util.LinkedList<>());
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.suplier.util.Work.jejak(id, "Membatalkan penulisan supply barang", d);
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }this.setVisible(false);
    entek();
    }//GEN-LAST:event_formInternalFrameClosing

    private void brgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brgItemStateChanged
        total.setEnabled(0<brg.getSelectedIndex());
        jum.setEnabled(0<brg.getSelectedIndex());
        analisaBarang();
    }//GEN-LAST:event_brgItemStateChanged

    private void jumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jumStateChanged
        if(!total.getText().isEmpty()&&total.isValid()){
            int x=Integer.parseInt(total.getText());
            if(x<=0)return;
        }else return;
        achmad.rifai.erp1.entity.ItemBeli i=null;
        java.util.List<achmad.rifai.erp1.entity.ItemBeli>l=p.getItems();
        for(int x=0;x<p.getItems().size();x++){
            achmad.rifai.erp1.entity.ItemBeli a=p.getItems().get(x);
            if(a.getBarang() == null ? brg.getItemAt(brg.getSelectedIndex()) == null : a.getBarang().equals(brg.getItemAt(brg.getSelectedIndex()))){
                i=a;
                l.remove(x);
                break;
            }
        }if(i==null){
            i=new achmad.rifai.erp1.entity.ItemBeli();
            i.setSatuan(genSatuan());
            i.setBarang(brg.getItemAt(brg.getSelectedIndex()));
        }i.setJumlah(Integer.parseInt(""+jum.getValue()));
        i.setHarga(org.joda.money.Money.of(CurrencyUnit.of("IDR"), Long.parseLong(total.getText())));
        l.add(i);
        refresh();
    }//GEN-LAST:event_jumStateChanged

    private void totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyReleased
        if(!total.getText().isEmpty()&&total.isValid()){
            int x=Integer.parseInt(total.getText());
            if(x<=0)return;
        }else return;
        achmad.rifai.erp1.entity.ItemBeli i=null;
        java.util.List<achmad.rifai.erp1.entity.ItemBeli>l=p.getItems();
        for(int x=0;x<p.getItems().size();x++){
            achmad.rifai.erp1.entity.ItemBeli a=p.getItems().get(x);
            if(a.getBarang() == null ? brg.getItemAt(brg.getSelectedIndex()) == null : a.getBarang().equals(brg.getItemAt(brg.getSelectedIndex()))){
                i=a;
                l.remove(x);
                break;
            }
        }if(i==null){
            i=new achmad.rifai.erp1.entity.ItemBeli();
            i.setBarang(brg.getItemAt(brg.getSelectedIndex()));
            i.setSatuan(genSatuan());
        }i.setJumlah(Integer.parseInt(""+jum.getValue()));
        i.setHarga(org.joda.money.Money.of(CurrencyUnit.of("IDR"), Long.parseLong(total.getText())));
        l.add(i);
        refresh();
    }//GEN-LAST:event_totalKeyReleased

    private void strukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_strukKeyReleased
        p.setStruk(struk.getText());
        refresh();
    }//GEN-LAST:event_strukKeyReleased

    private void supItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_supItemStateChanged
        p.setSuplier(sup.getItemAt(sup.getSelectedIndex()));
        refresh();
    }//GEN-LAST:event_supItemStateChanged

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        new Thread(this::jalan).start();
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        s.setEnabled(false);
        struk.setEnabled(false);
        sup.setEnabled(false);
        brg.setEnabled(false);
        jum.setEnabled(false);
        total.setEnabled(false);
    }//GEN-LAST:event_sActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jum;
    private javax.swing.JButton s;
    private javax.swing.JTextField struk;
    private javax.swing.JComboBox<String> sup;
    private javax.swing.JFormattedTextField total;
    // End of variables declaration//GEN-END:variables

    private void suplier() {
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        for(achmad.rifai.erp1.entity.Suplier s:new achmad.rifai.erp1.entity.dao.DAOSuplier(d).all()){
            sup.addItem(s.getKode());
            setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        }d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void barang() {
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        for(achmad.rifai.erp1.entity.Barang b:new achmad.rifai.erp1.entity.dao.DAOBarang(d).all()){
            brg.addItem(b.getKode());
            this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        }d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void analisaBarang() {
        achmad.rifai.erp1.entity.ItemBeli i=null;
        for(achmad.rifai.erp1.entity.ItemBeli a:p.getItems())
            if(a.getBarang() == null ? brg.getItemAt(brg.getSelectedIndex()) == null : a.getBarang().equals(brg.getItemAt(brg.getSelectedIndex()))){
            i=a;
            break;
        }if(i!=null){
            jum.setValue(i.getJumlah());
            total.setText(""+i.getHarga().getAmount().longValueExact());
        }else{
            jum.setValue(0);
            total.setText("0");
        }
    }

    private String genSatuan() {
        String sa="";try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.erp1.entity.Barang b=achmad.rifai.erp1.entity.Barang.of(d, brg.getItemAt(brg.getSelectedIndex()));
        if(b!=null)sa=b.getSatuan();
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }return sa;
    }

    private void refresh() {
        s.setEnabled(!struk.getText().isEmpty()&&0<sup.getSelectedIndex()&&!p.getItems().isEmpty());
    }

    private void jalan() {
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.suplier.util.Work.jejak(id, "Menyimpan pembelian baru", d);
        new achmad.rifai.erp1.entity.dao.DAOPembelian(d).insert(p);
        d.close();
        this.setVisible(false);
        entek();
    } catch (Exception ex) {
        enableAll();
        achmad.rifai.erp1.util.Db.hindar(ex);
    }
    }

    private void enableAll() {
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        struk.setEnabled(true);
        sup.setEnabled(true);
        brg.setEnabled(true);
        jum.setEnabled(true);
        total.setEnabled(true);
    }
}
