/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.admin.ui.karyawan;

import javax.swing.JOptionPane;

/**
 *
 * @author ai
 */
public class Detail extends javax.swing.JDialog {
private String id;
private achmad.rifai.erp1.entity.Karyawan k;
private java.awt.Frame f;
    /**
     * Creates new form Detail
     */
    public Detail(java.awt.Frame parent, boolean modal,String i,achmad.rifai.erp1.entity.Karyawan ka) {
        super(parent, modal);
        f=parent;
        id=i;
        k=ka;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JLabel();
        jabatan = new javax.swing.JLabel();
        telp = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        hire = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        blocked = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        masuk = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Karyawan ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        nama.setText("Nama : ???");

        jabatan.setText("Jabatan : ???");

        telp.setText("Telepon : ???");

        email.setText("Email : ???");

        hire.setText("Tanggal Masuk : ???");

        jButton1.setText("Ralat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        blocked.setText("blocked");
        jToolBar1.add(blocked);

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.add(jSeparator1);

        masuk.setText("masuk");
        jToolBar1.add(masuk);

        alamat.setEditable(false);
        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane3.setViewportView(alamat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(jabatan)
                            .addComponent(telp)
                            .addComponent(email)
                            .addComponent(hire))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jabatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        alamat.setText("");
        k.getAlamat().forEach((s)->{alamat.setText(alamat.getText()+s+"\n");});
        email.setText("Email : "+k.getEmail());
        this.setTitle("Detail Karyawan "+k.getId());
        hire.setText("Tanggal Masuk : "+k.getHiredate());
        jabatan.setText("Jabatan : "+k.getJabatan());
        nama.setText("Nama : "+k.getNama());
        telp.setText("Telepon : "+k.getTelp());
        if(k.isBlocked())blocked.setText("sedang dicekal");
        else blocked.setText("tidak dicekal");
        if(k.isMasuk())masuk.setText("sedang login");
        else masuk.setText("tidak login");
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Add(f,true,id,k).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x=JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghapus data ini?", "Hapus?", JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION)new Thread(() -> {
            try {
                setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
                achmad.rifai.admin.util.Work.jejak(id, "Menghapus data karyawan "+k.getId());
                achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
                achmad.rifai.erp1.entity.dao.DAOKaryawan dao=new achmad.rifai.erp1.entity.dao.DAOKaryawan(d);
                new Thread(() -> {achmad.rifai.admin.util.Work.hapusKaryawan(k);}).start();
                dao.delete(k);
                d.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                achmad.rifai.erp1.util.Db.hindar(ex);
            }setVisible(false);
        }).start();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JLabel blocked;
    private javax.swing.JLabel email;
    private javax.swing.JLabel hire;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jabatan;
    private javax.swing.JLabel masuk;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel telp;
    // End of variables declaration//GEN-END:variables
}
