/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.admin.ui.penjualan;

import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author ai
 */
public class Add extends javax.swing.JDialog {
private String id;
private achmad.rifai.erp1.entity.Penjualan p;
private java.awt.Frame f;
    /**
     * Creates new form Add
     */
    public Add(java.awt.Frame parent, boolean modal,String i,achmad.rifai.erp1.entity.Penjualan pe) {
        super(parent, modal);
        f=parent;
        id=i;
        p=pe;
        initComponents();
    }

    public Add(java.awt.Frame parent, boolean modal,String i) {
        super(parent, modal);
        f=parent;
        id=i;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ket = new javax.swing.JTextArea();
        tgl = new javax.swing.JComboBox<>();
        pelanggan = new javax.swing.JComboBox<>();
        nota = new javax.swing.JTextField();
        n = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pendataan Penjualan 1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nota");

        jLabel2.setText("Pelanggan");

        jLabel3.setText("Tanggal");

        jLabel4.setText("Keterangan");

        ket.setColumns(20);
        ket.setRows(5);
        ket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ketKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(ket);

        tgl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tglItemStateChanged(evt);
            }
        });

        pelanggan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pelangganItemStateChanged(evt);
            }
        });

        nota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                notaKeyReleased(evt);
            }
        });

        n.setText("Next");
        n.setEnabled(false);
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(191, 191, 191))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nota))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(n, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(n)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pelanggane();
        tgle();
        if(p!=null)inisial();
    }//GEN-LAST:event_formWindowOpened

    private void notaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_notaKeyReleased
        if(!nota.getText().isEmpty())try {
            achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
            achmad.rifai.erp1.entity.Penjualan pe=achmad.rifai.erp1.entity.Penjualan.of(d, nota.getText());
            if(pe!=null)nota.setForeground(Color.red);
            else nota.setForeground(Color.BLACK);
            d.close();
        } catch (Exception ex) {
            achmad.rifai.erp1.util.Db.hindar(ex);
        }refresh();
    }//GEN-LAST:event_notaKeyReleased

    private void pelangganItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pelangganItemStateChanged
        nota.setText(pelanggan.getItemAt(pelanggan.getSelectedIndex())+tgl.getSelectedItem());
        notaKeyReleased(null);
    }//GEN-LAST:event_pelangganItemStateChanged

    private void tglItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tglItemStateChanged
        nota.setText(pelanggan.getItemAt(pelanggan.getSelectedIndex())+tgl.getSelectedItem());
        notaKeyReleased(null);
    }//GEN-LAST:event_tglItemStateChanged

    private void ketKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ketKeyReleased
        refresh();
    }//GEN-LAST:event_ketKeyReleased

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        saving();
        new Add1(f,true,id,p).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int x=JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghentikan pendataan?", "Henti?", JOptionPane.YES_NO_OPTION);
        if(x!=JOptionPane.YES_OPTION){
            saving();
            new Add(f,true,id,p).setVisible(true);
        }this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ket;
    private javax.swing.JButton n;
    private javax.swing.JTextField nota;
    private javax.swing.JComboBox<String> pelanggan;
    private javax.swing.JComboBox<java.sql.Date> tgl;
    // End of variables declaration//GEN-END:variables

    private void pelanggane() {
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.erp1.entity.dao.DAOPelanggan dao=new achmad.rifai.erp1.entity.dao.DAOPelanggan(d);
        for(achmad.rifai.erp1.entity.Pelanggan p:dao.all())
            pelanggan.addItem(p.getKode());
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }
    }

    private void tgle() {
        java.sql.Date d1=java.sql.Date.valueOf(LocalDate.now()),d2;
        if(p!=null){
            if(p.getTgl().before(java.sql.Date.valueOf(d1.toLocalDate().minusYears(3))))d2=p.getTgl();
            else d2=java.sql.Date.valueOf(d1.toLocalDate().minusYears(3));
        }else d2=java.sql.Date.valueOf(d1.toLocalDate().minusYears(3));
        while(!d1.before(d2)){
            tgl.addItem(d1);
            d1=java.sql.Date.valueOf(d1.toLocalDate().minusDays(1));
        }
    }

    private void inisial() {
        ket.setText(p.getKet());
        nota.setText(p.getNota());
        pelanggan.setSelectedItem(p.getPelanggan());
        tgl.setSelectedItem(p.getTgl());
        n.setEnabled(true);
    }

    private void refresh() {
        n.setEnabled(!nota.getText().isEmpty()&&Color.BLACK==nota.getForeground()&&!ket.getText().isEmpty());
    }

    private void saving() {
        if(p==null){
            p=new achmad.rifai.erp1.entity.Penjualan();
            p.setDeleted(false);
        }p.setKet(ket.getText());
        p.setNota(nota.getText());
        p.setPelanggan(pelanggan.getItemAt(pelanggan.getSelectedIndex()));
        p.setTgl(tgl.getItemAt(tgl.getSelectedIndex()));
    }
}
