/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.suplier.ui.suplier;

import achmad.rifai.erp1.entity.Suplier;

/**
 *
 * @author janoko
 */
public abstract class ListSuplier extends javax.swing.JInternalFrame {
private String id;
public abstract void entek();
private Thread t;
    /**
     * Creates new form ListSuplier
     */
    public ListSuplier(String i) {
        id=i;
        initComponents();
        t=new Thread(()->{while(isVisible())try {
            reload();
            } catch (Exception ex) {
                achmad.rifai.erp1.util.Db.hindar(ex);
            }});t.setPriority(Thread.MAX_PRIORITY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        konten = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Daftar Pemasok");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        konten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(konten);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        t.stop();
        entek();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        t.start();
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
    }//GEN-LAST:event_formInternalFrameOpened

    private void reload() throws Exception {
        loadData();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Thread.sleep(5000);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable konten;
    // End of variables declaration//GEN-END:variables

    private void loadData() throws Exception {
        javax.swing.table.DefaultTableModel m=new javax.swing.table.DefaultTableModel(new String[]{"Kode","Nama","Alamat","Telepon"}, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };konten.setModel(m);
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        new achmad.rifai.erp1.entity.dao.DAOSuplier(d).all().forEach((Suplier s)->{
            String a="",tel="";
            a = s.getAlamat().stream().map((st) -> "["+st+"],").reduce(a, String::concat);
            tel = s.getTelp().stream().map((st) -> "["+st+"],").reduce(tel, String::concat);
            m.addRow(new Object[]{s.getKode(),s.getNama(),a,tel});
        });d.close();
    }
}
