/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.admin.ui.bonus;

import java.awt.Color;
import java.time.Month;
import java.time.Year;
import javax.swing.JOptionPane;

/**
 *
 * @author ai
 */
public class Add extends javax.swing.JDialog {
private String id;
private achmad.rifai.erp1.entity.BulanBonus b;
private int x=0,y=0;
    /**
     * Creates new form Add
     */
    public Add(java.awt.Frame parent, boolean modal,String i) {
        super(parent, modal);
        id=i;
        b=null;
        initComponents();
    }

    public Add(java.awt.Frame parent, boolean modal,String i,achmad.rifai.erp1.entity.BulanBonus bu) {
        super(parent, modal);
        id=i;
        b=bu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        peg = new javax.swing.JComboBox<>();
        bln = new javax.swing.JComboBox<>();
        thn = new javax.swing.JSpinner();
        kode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        s = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pendataan Bonus");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Kode :");

        jLabel2.setText("Pegawai :");

        jLabel3.setText("Bulan :");

        jLabel4.setText("Tahun :");

        thn.setModel(new javax.swing.SpinnerNumberModel(2017, 0, 2017, 1));

        kode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kodeKeyReleased(evt);
            }
        });

        lst.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(lst);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        s.setText("SAVE");
        s.setEnabled(false);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(peg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bln, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(thn, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                    .addComponent(kode))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(peg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(s))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(b!=null){
            saving();
            int x=JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menyimpan perubahan?", "SIMPAN?", JOptionPane.YES_NO_OPTION);
            if(x==JOptionPane.YES_OPTION)writeDB();
        }this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(()->{
            waktune();
            karyawane();
            if(b!=null)inisial();
            this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }).start();this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.GridBagConstraints gbc=new java.awt.GridBagConstraints();
        gbc.gridx=x;
        gbc.gridy=y;
        Bon bo=new Bon();
        bo.setVisible(true);
        lst.add(bo, gbc);
        x++;
        if(x==3){
            x=0;
            y++;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        saving();
        writeDB();
        this.setVisible(false);
    }//GEN-LAST:event_sActionPerformed

    private void kodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeKeyReleased
        if(!kode.getText().isEmpty())try {
            achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
            achmad.rifai.erp1.entity.BulanBonus bu=achmad.rifai.erp1.entity.BulanBonus.of(kode.getText(), d);
            if(bu==null)kode.setForeground(Color.red);
            else kode.setForeground(Color.BLACK);
            d.close();
        } catch (Exception ex) {
            achmad.rifai.erp1.util.Db.hindar(ex);
        }refresh();
    }//GEN-LAST:event_kodeKeyReleased

    private void saving() {
        if(b==null){
            b=new achmad.rifai.erp1.entity.BulanBonus();
            b.setDeleted(false);
        }b.setBln(bln.getItemAt(bln.getSelectedIndex()));
        b.setKode(kode.getText());
        b.setPeg(peg.getItemAt(peg.getSelectedIndex()));
        b.setThn(java.time.Year.of((int) thn.getValue()));
        java.util.List<achmad.rifai.erp1.entity.Bonusan>l=new java.util.LinkedList<>();
        for(javax.swing.JInternalFrame i:lst.getAllFrames()){
            Bon bo=(Bon) i;
            l.add(bo.genData());
        }b.setL(l);
    }

    private void writeDB() {
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.erp1.entity.BulanBonus bu=achmad.rifai.erp1.entity.BulanBonus.of(b.getKode(), d);
        achmad.rifai.erp1.entity.dao.DAOBulanBonus dao=new achmad.rifai.erp1.entity.dao.DAOBulanBonus(d);
        if(bu==null)dao.insert(b);
        else dao.update(bu, b);
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<java.time.Month> bln;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kode;
    private javax.swing.JDesktopPane lst;
    private javax.swing.JComboBox<String> peg;
    private javax.swing.JButton s;
    private javax.swing.JSpinner thn;
    // End of variables declaration//GEN-END:variables

    private void waktune() {
        bln.addItem(Month.JANUARY);
        bln.addItem(Month.FEBRUARY);
        bln.addItem(Month.MARCH);
        bln.addItem(Month.APRIL);
        bln.addItem(Month.MAY);
        bln.addItem(Month.JUNE);
        bln.addItem(Month.JULY);
        bln.addItem(Month.AUGUST);
        bln.addItem(Month.SEPTEMBER);
        bln.addItem(Month.OCTOBER);
        bln.addItem(Month.NOVEMBER);
        bln.addItem(Month.DECEMBER);
        thn.setModel(new javax.swing.SpinnerNumberModel(1900+Year.now().getValue(), 1900+Year.now().getValue(), 0, 1));
    }

    private void karyawane() {
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        java.util.List<achmad.rifai.erp1.entity.Karyawan>l=new achmad.rifai.erp1.entity.dao.DAOKaryawan(d).all();
        l.forEach((k)->{peg.addItem(k.getId());});
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }
    }

    private void inisial() {
        kode.setEnabled(false);
        kode.setText(b.getKode());
        bln.setSelectedItem(b.getBln());
        peg.setSelectedItem(b.getPeg());
        s.setEnabled(true);
        thn.setModel(new javax.swing.SpinnerNumberModel(1900+b.getThn().getValue(), 1900+Year.now().getValue(), 0, 1));
        allLST();
    }

    private void allLST() {
        b.getL().forEach((bo)->{
            java.awt.GridBagConstraints gbc=new java.awt.GridBagConstraints();
            gbc.gridx=x;
            gbc.gridy=y;
            Bon bon=new Bon();
            bon.setData(bo);
            bon.setVisible(true);
            lst.add(bon, gbc);
            x++;
            if(x==3){
                x=0;
                y++;
            }
        });
    }

    private void refresh() {
        s.setEnabled(!kode.getText().isEmpty()&&Color.BLACK==kode.getForeground());
    }
}
