/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.erp1.ui.pesan;

import achmad.rifai.erp1.util.Db;
import javax.swing.JOptionPane;

/**
 *
 * @author janoko
 */
public class Baca extends javax.swing.JDialog {
private achmad.rifai.erp1.entity.Karyawan k;
private achmad.rifai.erp1.entity.Pesan p;
    /**
     * Creates new form Baca
     */
    public Baca(java.awt.Frame parent, boolean modal, achmad.rifai.erp1.entity.Karyawan ka, achmad.rifai.erp1.entity.Pesan pe) {
        super(parent, modal);
        k=ka;
        p=pe;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pengirim = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        isi = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pengirim.setText("Pengirim : ???");

        waktu.setText("Waktu : ???");

        isi.setEditable(false);
        isi.setColumns(20);
        isi.setRows(5);
        jScrollPane1.setViewportView(isi);

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pengirim)
                            .addComponent(waktu))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pengirim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waktu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(()->{if(!terbaca())try {
            sejajarkan();
        } catch (Exception ex) {
            achmad.rifai.erp1.util.Db.hindar(ex);
        }}).start();this.setTitle("Pesan "+p.getKode());
        pengirim.setText("Pengirim : "+p.getPengirim());
        waktu.setText("Waktu : "+p.getWaktu());
        isi.setText(p.getPesan());
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x=JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghapus pesan "+p.getKode()+"?", "HAPUS?", JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION){
            new Thread(()->{try {
                sembunyi();
                } catch (Exception ex) {
                    achmad.rifai.erp1.util.Db.hindar(ex);
                }setVisible(false);
                dispose();
            }).start();
            this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sejajarkan() throws Exception {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.erp1.entity.Pesan a=achmad.rifai.erp1.entity.Pesan.of(d, p.getKode()),
                b=achmad.rifai.erp1.entity.Pesan.of(d, p.getKode());
        java.util.List<achmad.rifai.erp1.entity.Penerima>l=a.getKe();
        for(int x=0;x<l.size();x++){
            achmad.rifai.erp1.entity.Penerima pe=l.get(x);
            if(!pe.isTerbaca()&&(k.getId() == null ? pe.getAkun() == null : k.getId().equals(pe.getAkun()))){
                l.remove(x);
                pe.setTerbaca(true);
                l.add(pe);
                break;
            }
        }b.setKe(l);
        new achmad.rifai.erp1.entity.dao.DAOPesan(d).update(a, b);
        d.close();
    }

    private boolean terbaca() {
        boolean b=true;
        for(achmad.rifai.erp1.entity.Penerima pe:p.getKe())if(!pe.isTerbaca()&&(pe.getAkun() == null ? 
                k.getId() == null : pe.getAkun().equals(k.getId()))){
            b=false;
            break;
        }return b;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea isi;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pengirim;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables

    private void sembunyi() throws Exception {
        Db d=achmad.rifai.erp1.util.Work.loadDB();
        jejakSembunyi(d);
        kakure(d);
        d.close();
    }

    private void jejakSembunyi(Db d) throws Exception {
        achmad.rifai.erp1.entity.dao.DAOTracks dao=new achmad.rifai.erp1.entity.dao.DAOTracks(d);
        achmad.rifai.erp1.entity.Tracks a=dao.current(k.getId()),b=dao.current(k.getId());
        java.util.List<achmad.rifai.erp1.entity.Jejak>l=a.getL();
        l.add(new achmad.rifai.erp1.entity.Jejak("Menyembunyikan pesan "+p.getKode(), k.getId()));
        b.setL(l);
        dao.update(a, b);
    }

    private void kakure(Db d) throws Exception {
        achmad.rifai.erp1.entity.Pesan a=achmad.rifai.erp1.entity.Pesan.of(d, p.getKode()),b=achmad.rifai.erp1.entity.Pesan.of(d, p.getKode());
        java.util.List<achmad.rifai.erp1.entity.Penerima>l=a.getKe();
        for(int x=0;x<l.size();x++){
            achmad.rifai.erp1.entity.Penerima pe=l.get(x);
            if(k.getId() == null ? pe.getAkun() == null : k.getId().equals(pe.getAkun())){
                l.remove(x);
                pe.setSembunyi(true);
                l.add(pe);
                break;
            }
        }b.setKe(l);
        new achmad.rifai.erp1.entity.dao.DAOPesan(d).update(a, b);
    }
}
