/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.erp1.ui.pesan;

import achmad.rifai.erp1.util.Db;
import javax.swing.JOptionPane;

/**
 *
 * @author janoko
 */
public class Terkirim extends javax.swing.JDialog {
private achmad.rifai.erp1.entity.Karyawan k;
private achmad.rifai.erp1.entity.Pesan p;
    /**
     * Creates new form Terkirim
     */
    public Terkirim(java.awt.Frame parent, boolean modal, achmad.rifai.erp1.entity.Karyawan ka, achmad.rifai.erp1.entity.Pesan pe) {
        super(parent, modal);
        k=ka;
        p=pe;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ke = new javax.swing.JTextArea();
        waktu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        isi = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ke.setEditable(false);
        ke.setColumns(20);
        ke.setRows(5);
        ke.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ke);

        waktu.setText("Waktu : ???");

        isi.setEditable(false);
        isi.setColumns(20);
        isi.setRows(5);
        jScrollPane2.setViewportView(isi);

        jButton1.setText("HAPUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(waktu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waktu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        p.getKe().forEach((pe)->{ke.setText(ke.getText()+"["+pe.getAkun()+"],");});
        waktu.setText("Waktu : "+p.getWaktu());
        isi.setText(p.getPesan());
        this.setTitle("Pesan "+p.getKode());
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x=JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menghapus ini?", "HAPUS?", JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION){
            new Thread(()->{try {
                hapusDraft();
                } catch (Exception ex) {
                    Db.hindar(ex);
                }setVisible(false);
                dispose();}).start();
            this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea isi;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ke;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables

    private void hapusDraft() throws Exception {
        Db d=achmad.rifai.erp1.util.Work.loadDB();
        jejakHapus(d);
        hapusData(d);
        d.close();
    }

    private void jejakHapus(Db d) throws Exception {
        achmad.rifai.erp1.entity.dao.DAOTracks dao=new achmad.rifai.erp1.entity.dao.DAOTracks(d);
        achmad.rifai.erp1.entity.Tracks a=dao.current(k.getId()),b=dao.current(k.getId());
        java.util.List<achmad.rifai.erp1.entity.Jejak>l=a.getL();
        l.add(new achmad.rifai.erp1.entity.Jejak("Menghapus draft "+p.getKode(), k.getId()));
        b.setL(l);
        dao.update(a, b);
    }

    private void hapusData(Db d) throws Exception {
        new achmad.rifai.erp1.entity.dao.DAOPesan(d).delete(p);
    }
}