/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.suplier.ui;

import achmad.rifai.erp1.entity.Absen;
import achmad.rifai.erp1.entity.Karyawan;
import achmad.rifai.erp1.util.Db;
import javax.swing.JOptionPane;

/**
 *
 * @author ai
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        s = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login for SCM");

        jLabel1.setText("User Name :");

        jLabel2.setText("Password :");

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });

        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
        });

        s.setText("LOGIN");
        s.setEnabled(false);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id)
                            .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        s.setEnabled(!id.getText().isEmpty()&&!pass.getText().isEmpty());
    }//GEN-LAST:event_idKeyReleased

    private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased
        s.setEnabled(!id.getText().isEmpty()&&!pass.getText().isEmpty());
    }//GEN-LAST:event_passKeyReleased

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        new Thread(this::jalan).start();
        disableAll();
    }//GEN-LAST:event_sActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton s;
    // End of variables declaration//GEN-END:variables

    private void disableAll() {
        s.setEnabled(false);
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        id.setEnabled(false);
        pass.setEnabled(false);
    }

    private void jalan() {
        try {
            Db d=achmad.rifai.erp1.util.Work.loadDB();
            Karyawan k=Karyawan.of(d, id.getText());if(k!=null){
                if("pergudangan".equals(k.getJabatan())&&!k.isBlocked()&&!k.isDeleted()&&!k.isMasuk()){
                    if(pass.getText() == null ? k.getPass() == null : pass.getText().equals(k.getPass()))next(k);
                    else JOptionPane.showMessageDialog(rootPane, "Akses ditolak!");
                }else JOptionPane.showMessageDialog(rootPane, "Akses ditolak!");
            }else JOptionPane.showMessageDialog(rootPane, "ID tak dikenal!");d.close();
        } catch (Exception ex) {
            enableAll();
            Db.hindar(ex);
        }enableAll();
    }

    private void enableAll() {
        id.setText("");
        id.setEnabled(true);
        pass.setText("");
        pass.setEnabled(true);
        s.setEnabled(false);
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void next(Karyawan k) throws Exception {
        Db d=achmad.rifai.erp1.util.Work.loadDB();
        bloksek(k,d);
        absenJajal(k,d);
        achmad.rifai.suplier.util.Work.jejak(k.getId(),"Masuk kerja",d);
        masuk(k.getId());
        d.close();
    }

    private void bloksek(Karyawan k, Db d) throws Exception {
        Karyawan b=Karyawan.of(d, k.getId());
        b.setMasuk(true);
        new achmad.rifai.erp1.entity.dao.DAOKaryawan(d).update(k, b);
    }

    private void absenJajal(Karyawan k, Db d) throws Exception {
        achmad.rifai.erp1.entity.BukuAbsen bu=new achmad.rifai.erp1.entity.dao.DAOBukuAbsen(d).current();
        java.util.List<Absen>l=new java.util.LinkedList<>();
        bu.getL().forEach((a)->{if(a.getS() == null ? k.getId() == null : a.getS().equals(k.getId())){
            Absen an=new Absen();
            an.setS(k.getId());
            an.setL(Absen.Jenise.MASUK);
            l.add(an);
        }else l.add(a);});boolean yo=true;
        for(Absen a:l){
            if(a.getS() == null ? k.getId() == null : a.getS().equals(k.getId())){
                yo=false;
                break;
            }
        }if(yo){
            Absen an=new Absen();
            an.setS(k.getId());
            an.setL(Absen.Jenise.MASUK);
            l.add(an);
        }achmad.rifai.erp1.entity.BukuAbsen b=achmad.rifai.erp1.entity.BukuAbsen.of(d, bu.getTgl());
        b.setL(l);
        new achmad.rifai.erp1.entity.dao.DAOBukuAbsen(d).update(bu, b);
    }

    private void masuk(String id) {
        new Dash(id).setVisible(true);
        this.setVisible(false);
    }
}