/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.admin.ui.absen;

import achmad.rifai.erp1.entity.Absen;
import java.awt.Color;
import java.time.ZoneId;
import javax.swing.JOptionPane;

/**
 *
 * @author ai
 */
public class Add extends javax.swing.JDialog {
private String id;
private achmad.rifai.erp1.entity.BukuAbsen b;
    /**
     * Creates new form Add
     */
    public Add(java.awt.Frame parent, boolean modal,String i) {
        super(parent, modal);
        id=i;
        b=null;
        initComponents();
    }

    public Add(java.awt.Frame parent, boolean modal,String i,achmad.rifai.erp1.entity.BukuAbsen bu) {
        super(parent, modal);
        id=i;
        b=bu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tgl = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst = new javax.swing.JDesktopPane();
        s = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Tanggal");

        tgl.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        tgl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tglStateChanged(evt);
            }
        });
        tgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tglKeyReleased(evt);
            }
        });

        lst.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(lst);

        s.setText("SAVE");
        s.setEnabled(false);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 189, Short.MAX_VALUE))
                    .addComponent(s, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tglKeyReleased

    private void tglStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tglStateChanged
        java.util.Date t=(java.util.Date) tgl.getValue();
        java.sql.Date sq=java.sql.Date.valueOf(t.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.erp1.entity.BukuAbsen bu=achmad.rifai.erp1.entity.BukuAbsen.of(d, ""+sq);
        if(bu!=null)tgl.setForeground(Color.red);
        else tgl.setForeground(Color.BLACK);
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }refresh();
    }//GEN-LAST:event_tglStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(this::muatKaryawan).start();
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
    }//GEN-LAST:event_formWindowOpened

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        saving();
        writeDB();
        this.setVisible(false);
    }//GEN-LAST:event_sActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(b!=null){
            saving();
            int x=JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin menyimpan perubahan?", "SIMPAN?", JOptionPane.YES_NO_OPTION);
            if(x==JOptionPane.YES_OPTION)writeDB();
        }this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDesktopPane lst;
    private javax.swing.JButton s;
    private javax.swing.JSpinner tgl;
    // End of variables declaration//GEN-END:variables

    private void refresh() {
        s.setEnabled(Color.BLACK==tgl.getForeground());
    }

    private void muatKaryawan() {
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        java.util.List<achmad.rifai.erp1.entity.Karyawan>l=new achmad.rifai.erp1.entity.dao.DAOKaryawan(d).all();
        int x=0,y=0;
        for(achmad.rifai.erp1.entity.Karyawan k:l){
            java.awt.GridBagConstraints gbc=new java.awt.GridBagConstraints();
            gbc.gridx=x;
            gbc.gridy=y;
            Abs a=new Abs(k.getId());
            a.setVisible(true);
            lst.add(a, gbc);
            x++;
            if(x==3){
                x=0;
                y++;
            }
        }d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }muatLanjut();
    }

    private void saving() {
        if(b==null){
            b=new achmad.rifai.erp1.entity.BukuAbsen();
            b.setDeleted(true);
        }java.util.Date t=(java.util.Date) tgl.getValue();
        java.sql.Date sq=java.sql.Date.valueOf(t.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        b.setTgl(""+sq);
        java.util.List<Absen>l=new java.util.LinkedList<>();
        for(javax.swing.JInternalFrame i:lst.getAllFrames()){
            Abs a=(Abs) i;
            l.add(a.genAbsen());
        }b.setL(l);
    }

    private void writeDB() {
    try {
        achmad.rifai.admin.util.Work.jejak(id, "Mendata Buku Absen tanggal "+b.getTgl());
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.erp1.entity.dao.DAOBukuAbsen dao=new achmad.rifai.erp1.entity.dao.DAOBukuAbsen(d);
        achmad.rifai.erp1.entity.BukuAbsen bu=achmad.rifai.erp1.entity.BukuAbsen.of(d, b.getTgl());
        if(bu==null)dao.insert(b);
        else dao.update(bu, b);
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }
    }

    private void muatLanjut() {
        if(b!=null){
            java.sql.Date t=java.sql.Date.valueOf(b.getTgl());
            tgl.setEnabled(false);
            tgl.setValue(t);
            b.getL().forEach((a)->{filling(a);});
            s.setEnabled(true);
        }this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    private void filling(Absen a) {
        for(javax.swing.JInternalFrame i:lst.getAllFrames()){
            Abs ab=(Abs) i;
            if(a.getS() == null ? ab.getKaryawan() == null : a.getS().equals(ab.getKaryawan())){
                ab.setL(a.getL());
                break;
            }
        }
    }
}