/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package achmad.rifai.admin.ui.tracks;

import java.awt.Color;
import java.time.Month;
import javax.swing.JOptionPane;

/**
 *
 * @author ai
 */
public class Add extends javax.swing.JDialog {
private String id;
private achmad.rifai.erp1.entity.Tracks t;
private int x=0,y=0;
    /**
     * Creates new form Add
     */
    public Add(java.awt.Frame parent, boolean modal,String i) {
        super(parent, modal);
        id=i;
        t=null;
        initComponents();
    }

    public Add(java.awt.Frame parent, boolean modal,String i,achmad.rifai.erp1.entity.Tracks tr) {
        super(parent, modal);
        id=i;
        t=tr;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        karyawan = new javax.swing.JComboBox<>();
        kode = new javax.swing.JTextField();
        bln = new javax.swing.JComboBox<>();
        thn = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        s = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Kode");

        jLabel2.setText("Pekerja");

        jLabel3.setText("Bulan");

        jLabel4.setText("Tahun");

        karyawan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                karyawanItemStateChanged(evt);
            }
        });

        kode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kodeKeyReleased(evt);
            }
        });

        bln.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                blnItemStateChanged(evt);
            }
        });

        thn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        thn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                thnKeyReleased(evt);
            }
        });

        lst.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(lst);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        s.setText("SAVE");
        s.setEnabled(false);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kode)
                                        .addComponent(karyawan, 0, 346, Short.MAX_VALUE)
                                        .addComponent(bln, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(s))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(()->{
            karyawane();
            ulane();
            if(t!=null)inisial();
            this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }).start();this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
    }//GEN-LAST:event_formWindowOpened

    private void kodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeKeyReleased
        if(!kode.getText().isEmpty())try {
            achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
            achmad.rifai.erp1.entity.Tracks tr=achmad.rifai.erp1.entity.Tracks.of(d, kode.getText());
            if(tr!=null)kode.setForeground(Color.red);
            else kode.setForeground(Color.BLACK);
            d.close();
        } catch (Exception ex) {
            achmad.rifai.erp1.util.Db.hindar(ex);
        }refresh();
    }//GEN-LAST:event_kodeKeyReleased

    private void karyawanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_karyawanItemStateChanged
        refresh();
    }//GEN-LAST:event_karyawanItemStateChanged

    private void blnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_blnItemStateChanged
        refresh();
    }//GEN-LAST:event_blnItemStateChanged

    private void thnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thnKeyReleased
        if(!thn.getText().isEmpty()&&thn.isValid()){
            int xa=Integer.parseInt(thn.getText());
            if(xa<=0)thn.setForeground(Color.red);
            else thn.setForeground(Color.BLACK);
        }refresh();
    }//GEN-LAST:event_thnKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.GridBagConstraints gbc=new java.awt.GridBagConstraints();
        gbc.gridx=x;
        gbc.gridy=y;
        Loge l=new Loge();
        l.setVisible(true);
        lst.add(l, gbc);
        x++;
        if(x==3){
            y++;
            x=0;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        saving();
        writeDB();
        this.setVisible(false);
    }//GEN-LAST:event_sActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(t!=null){
            saving();
            int x=JOptionPane.showConfirmDialog(rootPane, "Apa anda ingin mneyimpan perubahan?", "SIMPAN?", JOptionPane.YES_NO_OPTION);
            if(x==JOptionPane.YES_OPTION)writeDB();
        }this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<java.time.Month> bln;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> karyawan;
    private javax.swing.JTextField kode;
    private javax.swing.JDesktopPane lst;
    private javax.swing.JButton s;
    private javax.swing.JFormattedTextField thn;
    // End of variables declaration//GEN-END:variables

    private void karyawane() {
    try {
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        java.util.List<achmad.rifai.erp1.entity.Karyawan>l=new achmad.rifai.erp1.entity.dao.DAOKaryawan(d).all();
        l.forEach((k)->{karyawan.addItem(k.getId());});
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }
    }

    private void ulane() {
        bln.addItem(Month.JANUARY);
        bln.addItem(Month.FEBRUARY);
        bln.addItem(Month.MARCH);
        bln.addItem(Month.APRIL);
        bln.addItem(Month.MAY);
        bln.addItem(Month.JUNE);
        bln.addItem(Month.JULY);
        bln.addItem(Month.AUGUST);
        bln.addItem(Month.SEPTEMBER);
        bln.addItem(Month.OCTOBER);
        bln.addItem(Month.NOVEMBER);
        bln.addItem(Month.DECEMBER);
    }

    private void inisial() {
        kode.setEnabled(false);
        kode.setText(t.getKode());
        karyawan.setSelectedItem(t.getId());
        bln.setSelectedItem(t.getBln());
        thn.setText(""+(1900+t.getTahun()));
        isiLST();
    }

    private void isiLST() {
        t.getL().forEach((j)->{
            java.awt.GridBagConstraints gbc=new java.awt.GridBagConstraints();
            gbc.gridy=y;
            gbc.gridx=x;
            Loge l=new Loge();
            l.setAksei(j.getAksi());
            l.setWaktu(j.getWaktu());
            l.setVisible(true);
            lst.add(l, gbc);
            x++;
            if(x==3){
                y++;
                x=0;
            }
        });s.setEnabled(true);
    }

    private void refresh() {
        s.setEnabled(!kode.getText().isEmpty()&&!thn.getText().isEmpty()&&Color.BLACK==kode.getForeground()&&thn.isValid()&&
        Color.BLACK==thn.getForeground());
    }

    private void saving() {
        if(t==null){
            t=new achmad.rifai.erp1.entity.Tracks();
            t.setDeleted(false);
        }t.setKode(kode.getText());
        t.setId(karyawan.getItemAt(karyawan.getSelectedIndex()));
        t.setBln(bln.getItemAt(bln.getSelectedIndex()));
        t.setTahun(Integer.parseInt(thn.getText())-1900);
        java.util.List<achmad.rifai.erp1.entity.Jejak>l=new java.util.LinkedList<>();
        for(javax.swing.JInternalFrame i:lst.getAllFrames()){
            Loge lo=(Loge) i;
            l.add(lo.genJejak());
        }t.setL(l);
    }

    private void writeDB() {
    try {
        achmad.rifai.admin.util.Work.jejak(id, "Mendata buku perilaku "+t.getKode());
        achmad.rifai.erp1.util.Db d=achmad.rifai.erp1.util.Work.loadDB();
        achmad.rifai.erp1.entity.Tracks tr=achmad.rifai.erp1.entity.Tracks.of(d, t.getKode());
        achmad.rifai.erp1.entity.dao.DAOTracks dao=new achmad.rifai.erp1.entity.dao.DAOTracks(d);
        if(tr==null)dao.insert(t);
        else dao.update(tr, t);
        d.close();
    } catch (Exception ex) {
        achmad.rifai.erp1.util.Db.hindar(ex);
    }
    }
}
